In [2]:
import pandas as pd
food_coded=pd.read_csv("food_coded.csv")
food_coded

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1,1,610,4.0,420.0,2,"wine. mac and cheese, pizza, ice cream",boredom and sadness,NaN,...,1.0,1.0,5,940.0,500,Softball,5,1,1315,156
121,3,1,1,265,2.0,315.0,2,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,NaN,...,1.0,NaN,4,940.0,500,basketball,5,2,1315,180
122,3.882,1,1,720,NaN,420.0,1,"rice, potato, seaweed soup",sadness,NaN,...,1.0,2.0,5,580.0,690,none,4,2,1315,120
123,3,2,1,720,4.0,420.0,1,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",NaN,...,2.0,2.0,1,940.0,500,NaN,3,1,1315,135
124,3.9,1,1,430,NaN,315.0,2,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",NaN,...,1.0,2.0,2,725.0,345,NaN,4,2,575,135

In [3]:
food_coded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          123 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   99 non-null     object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [4]:
food_coded.describe()

,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food_reasons_coded,cook,comfort_food_reasons_coded.1,cuisine,...,persian_food,self_perception_weight,soup,sports,thai_food,tortilla_calories,turkey_calories,veggies_day,vitamins,waffle_calories
count,125.000000,125.000000,125.000000,106.000000,124.000000,125.00000,106.000000,122.000000,125.000000,108.000000,...,124.000000,124.000000,124.000000,123.000000,125.000000,124.000000,125.000000,125.000000,125.000000,125.000000
mean,1.392000,1.112000,577.320000,3.028302,505.241935,1.75200,2.698113,2.786885,2.688000,1.388889,...,2.806452,3.120968,1.217742,1.390244,3.336000,947.580645,555.040000,4.008000,1.512000,1073.400000
std,0.490161,0.316636,131.214156,0.639308,230.840506,0.43359,1.972042,1.038351,1.910987,0.974759,...,1.423824,1.115980,0.414385,0.489800,1.436528,202.090179,152.370379,1.081337,0.501867,248.667092
min,1.000000,1.000000,265.000000,2.000000,315.000000,1.00000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,580.000000,345.000000,1.000000,1.000000,575.000000
25%,1.000000,1.000000,430.000000,3.000000,420.000000,2.00000,2.000000,2.000000,2.000000,1.000000,...,2.000000,2.000000,1.000000,1.000000,2.000000,725.000000,500.000000,3.000000,1.000000,900.000000
50%,1.000000,1.000000,610.000000,3.000000,420.000000,2.00000,2.000000,3.000000,2.000000,1.000000,...,3.000000,3.000000,1.000000,1.000000,3.000000,940.000000,500.000000,4.000000,2.000000,900.000000
75%,2.000000,1.000000,720.000000,3.000000,420.000000,2.00000,3.000000,3.000000,3.000000,1.000000,...,4.000000,4.000000,1.000000,2.000000,5.000000,1165.000000,690.000000,5.000000,2.000000,1315.000000
max,2.000000,2.000000,720.000000,4.000000,980.000000,2.00000,9.000000,5.000000,9.000000,6.000000,...,5.000000,6.000000,2.000000,2.000000,5.000000,1165.000000,850.000000,5.000000,2.000000,1315.000000

In [5]:
null_counts = food_coded.isnull().sum()
print(null_counts)

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         26
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [6]:
null_counts = food_coded.isnull().sum()
columns_with_nulls = null_counts[null_counts > 0]
for col in columns_with_nulls.index:
    print(f"Column: {col}, Null Values: {columns_with_nulls[col]}, Data Type: {food_coded[col].dtype}")

Column: GPA, Null Values: 2, Data Type: object
Column: calories_day, Null Values: 19, Data Type: float64
Column: calories_scone, Null Values: 1, Data Type: float64
Column: comfort_food, Null Values: 1, Data Type: object
Column: comfort_food_reasons, Null Values: 2, Data Type: object
Column: comfort_food_reasons_coded, Null Values: 19, Data Type: float64
Column: cook, Null Values: 3, Data Type: float64
Column: cuisine, Null Values: 17, Data Type: float64
Column: diet_current, Null Values: 1, Data Type: object
Column: drink, Null Values: 2, Data Type: float64
Column: eating_changes, Null Values: 3, Data Type: object
Column: employment, Null Values: 9, Data Type: float64
Column: exercise, Null Values: 13, Data Type: float64
Column: father_education, Null Values: 1, Data Type: float64
Column: father_profession, Null Values: 3, Data Type: object
Column: fav_cuisine, Null Values: 2, Data Type: object
Column: fav_food, Null Values: 2, Data Type: float64
Column: food_childhood, Null Values: 1, Data Type: object
Column: healthy_meal, Null Values: 1, Data Type: object
Column: ideal_diet, Null Values: 1, Data Type: object
Column: income, Null Values: 1, Data Type: float64
Column: life_rewarding, Null Values: 1, Data Type: float64
Column: marital_status, Null Values: 1, Data Type: float64
Column: meals_dinner_friend, Null Values: 3, Data Type: object
Column: mother_education, Null Values: 3, Data Type: float64
Column: mother_profession, Null Values: 2, Data Type: object
Column: on_off_campus, Null Values: 1, Data Type: float64
Column: persian_food, Null Values: 1, Data Type: float64
Column: self_perception_weight, Null Values: 1, Data Type: float64
Column: soup, Null Values: 1, Data Type: float64
Column: sports, Null Values: 2, Data Type: float64
Column: tortilla_calories, Null Values: 1, Data Type: float64
Column: type_sports, Null Values: 26, Data Type: object
Column: weight, Null Values: 2, Data Type: object

In [7]:
numeric_col = food_coded.select_dtypes(include=['number']).columns
numeric_col = list(numeric_col)
x=food_coded[numeric_col].isnull().sum()
print(x)

Gender                           0
breakfast                        0
calories_chicken                 0
calories_day                    19
calories_scone                   1
coffee                           0
comfort_food_reasons_coded      19
cook                             3
comfort_food_reasons_coded.1     0
cuisine                         17
diet_current_coded               0
drink                            2
eating_changes_coded             0
eating_changes_coded1            0
eating_out                       0
employment                       9
ethnic_food                      0
exercise                        13
father_education                 1
fav_cuisine_coded                0
fav_food                         2
fries                            0
fruit_day                        0
grade_level                      0
greek_food                       0
healthy_feeling                  0
ideal_diet_coded                 0
income                           1
indian_food                      0
italian_food                     0
life_rewarding                   1
marital_status                   1
mother_education                 3
nutritional_check                0
on_off_campus                    1
parents_cook                     0
pay_meal_out                     0
persian_food                     1
self_perception_weight           1
soup                             1
sports                           2
thai_food                        0
tortilla_calories                1
turkey_calories                  0
veggies_day                      0
vitamins                         0
waffle_calories                  0
dtype: int64

In [8]:
categorical_cols = food_coded.select_dtypes('object').columns.tolist()
y=food_coded[categorical_cols].isnull().sum()
print(y)

GPA                      2
comfort_food             1
comfort_food_reasons     2
diet_current             1
eating_changes           3
father_profession        3
fav_cuisine              2
food_childhood           1
healthy_meal             1
ideal_diet               1
meals_dinner_friend      3
mother_profession        2
type_sports             26
weight                   2
dtype: int64

In [9]:
duplicate_rows = food_coded.duplicated().any()
duplicate_columns = food_coded.columns.duplicated().any()
if duplicate_rows:
    print("The dataset has duplicate rows.")
else:
    print("The dataset does not have duplicate rows.")
if duplicate_columns:
    print("The dataset has duplicate columns.")
else:
    print("The dataset does not have duplicate columns.")

The dataset does not have duplicate rows.
The dataset does not have duplicate columns.

In [10]:
from sklearn.impute import SimpleImputer
numeric_imputer = SimpleImputer(strategy='mean')
categorical_imputer = SimpleImputer(strategy='most_frequent')

In [12]:
numeric_cols = food_coded.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = food_coded.select_dtypes(include=['object']).columns
food_coded[numeric_cols] = numeric_imputer.fit_transform(food_coded[numeric_cols])
food_coded[categorical_cols] = categorical_imputer.fit_transform(food_coded[categorical_cols])
new_data=food_coded

In [13]:
new_data

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2.0,1.0,430.0,3.028302,315.0,1.0,none,we dont have comfort,9.000000,...,1.0,1.000000,1.0,1165.0,345.0,car racing,5.0,1.0,1315.0,187
1,3.654,1.0,1.0,610.0,3.000000,420.0,2.0,"chocolate, chips, ice cream","Stress, bored, anger",1.000000,...,1.0,1.000000,2.0,725.0,690.0,Basketball,4.0,2.0,900.0,155
2,3.3,1.0,1.0,720.0,4.000000,420.0,2.0,"frozen yogurt, pizza, fast food","stress, sadness",1.000000,...,1.0,2.000000,5.0,1165.0,500.0,none,5.0,1.0,900.0,I'm not answering this.
3,3.2,1.0,1.0,430.0,3.000000,420.0,2.0,"Pizza, Mac and cheese, ice cream",Boredom,2.000000,...,1.0,2.000000,5.0,725.0,690.0,none,3.0,1.0,1315.0,"Not sure, 240"
4,3.5,1.0,1.0,720.0,2.000000,420.0,2.0,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.000000,...,1.0,1.000000,4.0,940.0,500.0,Softball,4.0,2.0,760.0,190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3.5,1.0,1.0,610.0,4.000000,420.0,2.0,"wine. mac and cheese, pizza, ice cream",boredom and sadness,2.698113,...,1.0,1.000000,5.0,940.0,500.0,Softball,5.0,1.0,1315.0,156
121,3,1.0,1.0,265.0,2.000000,315.0,2.0,Pizza / Wings / Cheesecake,Loneliness / Homesick / Sadness,2.698113,...,1.0,1.390244,4.0,940.0,500.0,basketball,5.0,2.0,1315.0,180
122,3.882,1.0,1.0,720.0,3.028302,420.0,1.0,"rice, potato, seaweed soup",sadness,2.698113,...,1.0,2.000000,5.0,580.0,690.0,none,4.0,2.0,1315.0,120
123,3,2.0,1.0,720.0,4.000000,420.0,1.0,"Mac n Cheese, Lasagna, Pizza","happiness, they are some of my favorite foods",2.698113,...,2.0,2.000000,1.0,940.0,500.0,none,3.0,1.0,1315.0,135
124,3.9,1.0,1.0,430.0,3.028302,315.0,2.0,"Chocolates, pizza, and Ritz.","hormones, Premenstrual syndrome.",2.698113,...,1.0,2.000000,2.0,725.0,345.0,none,4.0,2.0,575.0,135

In [15]:
new_data.isnull().sum()

GPA                 0
Gender              0
breakfast           0
calories_chicken    0
calories_day        0
                   ..
type_sports         0
veggies_day         0
vitamins            0
waffle_calories     0
weight              0
Length: 61, dtype: int64